name: Build
run-name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-sphinx python3-sphinx-rtd-theme python3-myst-parser
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: |
            *.js
            *.json
            LICENSE
            README.md
